### PR TITLE
Update to Cadence v1.0.0-preview.25

### PR DESCRIPTION
**Pull request by turbolent**
## Description

Automatically update to:
- [onflow/cadence v1.0.0-preview.25](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.25)
- [onflow/flow-go-sdk v1.0.0-preview.25](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.25)
- [onflow/flow-go v0.34.0-crescendo-preview.18](https://github.com/onflow/flow-go/releases/tag/v0.34.0-crescendo-preview.18)
- [onflow/flow-emulator v1.0.0-preview.22](https://github.com/onflow/flow-emulator/releases/tag/v1.0.0-preview.22)

### CODE REVIEW

**Review by jribbink — APPROVED** [review]

**Comment by sideninja** [comment]
Some mocking issues @jribbink can you take a look

**Comment by jribbink** [comment]
yup, on it 👍

**Comment by turbolent** [comment]
Thank you so much for making those adjustments @jribbink! 🙏

**Comment by turbolent** [comment]
Cancelled CI because Codecov stalled, but the tests actually succeeded: https://github.com/onflow/flowkit/actions/runs/8928379482/job/24523835234?pr=40

**Pull request merged**
